travis:
  secure:
    BINSTAR_TOKEN: l6XSa2QulCCWK+vywx64usPU9sZcFZbEJt7TzFrRcnFRKyZ7zLt4fpqp5JDAVw9MKLFFvj2yTuWmVPKFdTOIzAr1vJ2TMWNI7XkVmLLslAfGAA117Qq1e5sQ1Mo7Fq9Qg6HMwhYyPYBIHWzG6/8ji6nvCkufiVwEr5bCH5jNWjJzWFvtbVAfCNL2CV9K7WCzJBw+6dIWEclLYgT5MI8DMRN1yiwlQm6Kyw5MWPZZ5CW27dEy718KdIyFutAeoli7mMuigslY9yBqVaBeQ9uAul61QRuCQTqL+MpKwPV+mh8Xb6ksXOBiKdi44A3ICwAnClCGyWpItVr+eCLTvDs+6v9QBhMVyXLPC0ykAxYunhBtNOnV4QVyxpgzrDWEvTWqyP5/nRMLHUdeWDj39axIiojALAjxWiKK8d0Qi8guVwI1c9rCFCaSAhLddbQTicNmQhFelFmHPcwH4zPurdfG++Yf1pwNsKRGdJuZiH6igf26E2GcU3Akd2/OsR/DwwuecoJAYFBSOp8Gg4FW3FAs9bCVlM9HXiOOkZj0dIaRuJOjIERjwDTZLvFL5ekefJbd54IEssnL+7LUD9vVdN873mScMzKyMPEPICjXIQNqZKZ96OGJ8K099ujKvH9EXU8uZNjn5QhCOMpzOIoD+ydxYuM8PYjb2bL2KQpU9l1jtaM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
